### ISSUE TITLE
some problems about part_refiner

### ISSUE THREAD

**Issue by CRISZJ** [Hao-HUST/G2LGAN#4]
Thanks for your code,but when I use the file that named seperate_part_mat.py,the iteration seems to be going on all the time, I ran for a day, but in the end RAM was completely occupied and forced to stop, so I would like to ask what is going on. I noticed that some decompiled files will be generated after decompressing input_data. Which files need to be deleted?

**Comment by Hao-HUST** [comment]
I think you can use a small dataset, like 100 real shape data with 32-res and 64-res, to make a test. 

If "seperate_part_mat.py" script works on such a small dataset, maybe your RAM size is small, compared to the data size.

**Comment by CRISZJ** [comment]
Thanks for your reply,I want to know the end of the process about seperate_part_mat.py.Because  when I run the file, the program iterates 3047 times and restarts the iteration again, how can I terminate it?

**Comment by Hao-HUST** [comment]
The script is used to separate each semantic parts from training data(the original shape is constituted by multiple semantical parts) and combine these parts into several npy files, like part_1.npy, part_2,.npy, ..., part_n.npy. 

The program iterates 3047 times because there 3047 model shapes on your training data, and restarts the iteration again because you need to make the loop twice for 32-res and 64-res both. If you want to end the script, just type Ctrl+c.
